export const shapeLabels = {
  wobbi: 'Wobbi',
  ghost: 'Fantôme',
  circle: 'Rond',
  'rounded-square': 'Carré arrondi',
  cloud: 'Nuage',
  drop: 'Goutte',
  oval: 'Ovale',
  egg: 'Œuf',
  custom: 'Personnalisée',
};
export const eyeLabels = {
  classic: 'Grands yeux',
  round: 'Ronds',
  capsules: 'Capsules',
  dots: 'Points',
  asymmetric: 'Asymétriques',
  pixel: 'Pixels',
  sleepy: 'Paupières',
  angry: 'Anguleux',
  'side-eye': 'De côté',
  wink: 'Clin d’œil',
  lashed: 'Cils',
  bubble: 'Bulle',
  winged: 'Envolé',
  custom: 'Personnalisés',
};
export const irisLabels = {
  dot: 'Simple',
  glossy: 'Brillant',
  money: 'Dollars',
  heart: 'Cœur',
  star: 'Étoile',
  swirl: 'Tourbillon',
  rings: 'Anneaux',
  pinwheel: 'Vrille',
  veil: 'Voile',
  slit: 'Fente',
  flower: 'Fleur',
  clock: 'Horloge',
  custom: 'Personnalisé',
};
export const noseLabels = {
  none: 'Sans',
  dot: 'Petit nez',
  round: 'Nez rond',
  button: 'Bouton',
  hook: 'Crochet',
  nostrils: 'Narines',
  pointy: 'Pointu',
  muzzle: 'Museau',
  moustache: 'Moustache',
  beak: 'Bec',
  custom: 'Personnalisé',
};
export const browLabels = {
  none: 'Sans',
  soft: 'Doux',
  straight: 'Droits',
  arched: 'Arquées',
  worried: 'Inquiets',
  custom: 'Personnalisés',
};
export const mouthLabels = {
  none: 'Sans',
  smile: 'Sourire',
  open: 'Ouverte',
  tooth: 'Deux dents',
  small: 'Petit trait',
  grin: 'Grand sourire',
  pout: 'Moue',
  fangs: 'Crocs',
  custom: 'Personnalisée',
};
export const headLabels = {
  none: 'Sans',
  tuft: 'Mèche',
  curl: 'Boucle',
  spiky: 'Épis',
  bun: 'Chignon',
  fringe: 'Frange',
  blaze: 'Épis flamboyants',
  mane: 'Crinière',
  'wild-mane': 'Toison sauvage',
  'custom-hair': 'Personnalisés',
  'bunny-ears': 'Oreilles de lapin',
  ears: 'Oreilles de chat',
  'round-ears': 'Oreilles rondes',
  'elf-ears': 'Oreilles d’elfe',
  horns: 'Cornes',
  halo: 'Auréole',
};
export const headGroups = [
  {
    title: 'Cheveux',
    itemLabel: 'cheveux',
    values: [
      'tuft',
      'curl',
      'spiky',
      'bun',
      'fringe',
      'blaze',
      'mane',
      'wild-mane',
      'custom-hair',
    ],
  },
  {
    title: 'Oreilles',
    itemLabel: 'oreilles',
    values: ['bunny-ears', 'ears', 'round-ears', 'elf-ears'],
  },
  { title: 'Détails', itemLabel: 'détails', values: ['horns', 'halo'] },
];
export const accessoryLabels = {
  none: 'Sans',
  glasses: 'Lunettes',
  sunglasses: 'Lunettes de soleil',
  headphones: 'Casque',
  bowtie: 'Nœud papillon',
  monocle: 'Monocle',
  blush: 'Joues roses',
  freckles: 'Taches de rousseur',
  bandage: 'Pansement',
  'fox-tail': 'Queue de renard',
  'cat-tail': 'Queue de chat',
};
export const reactionLabels = {
  idle: 'Repos',
  happy: 'Joie',
  thinking: 'Réflexion',
  surprised: 'Surprise',
  sad: 'Peur',
  error: 'Colère',
  success: 'Réussite',
  loading: 'Attente',
  sleeping: 'Sommeil',
  singing: 'Chant',
};
export const palette = ['#111218', '#ffffff', '#9270ff', '#61a9ff', '#ffcc45'];
